server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  application:
    name: mate
  mvc:
    problemdetails:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18099
  datasource:
    url: jdbc:mysql://localhost:3306/mate?useUnicode=true&characterEncoding=utf8&useSSL=false&connectionTimeZone=UTC&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: mateadmin
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true
    oauth:
      client-id: messaging-client
      client-secret: secret
      scopes: profile,openid
  authorization-code:
    authorizationUrl: http://127.0.0.1:19090/oauth2/authorize
    tokenUrl: http://127.0.0.1:19090/oauth2/token


logging:
  level:
    root: info
    org:
      springframework:
        web: info
        security: debug
      pf4j: debug
