server:
  port: 18090
  servlet:
    context-path: /

spring:
  application:
    name: mate
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-secret: bd0DNrDKSzOcDcL1crFgBIy0qaF4hHIgD4ypixaWonA1uGpFzCusZ0xXZfjDo1Kc
          client-id: 275320595195953156@mate
          introspection-uri: http://localhost:8080/oauth/v2/introspect
  datasource:
    url: jdbc:postgresql://localhost:5432/mate
    username: mateadmin
    password: mateadmin
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true



logging:
  level:
    root: info
    org:
      springframework:
        web: info
        security: debug
