version: '3.8'

services:
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --config /config.yaml --steps /init-step.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '3333:3333'
    volumes:
      - './config/config.yaml:/config.yaml:ro'
      - './config/init-step.yaml:/init-step.yaml:ro'

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data:rw'

  zipkin:
    restart: 'always'
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
