version: '3.8'

services:
  mysql:
    restart: unless-stopped
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MyNewPass4!
    ports:
      - '3306:3306'
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"
